# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rj/Documents/VSCode/StackClone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rj/Documents/VSCode/StackClone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rj/Documents/VSCode/StackClone/CMakeFiles /Users/rj/Documents/VSCode/StackClone//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rj/Documents/VSCode/StackClone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StackClone

# Build rule for target.
StackClone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StackClone
.PHONY : StackClone

# fast build rule for target.
StackClone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackClone.dir/build.make CMakeFiles/StackClone.dir/build
.PHONY : StackClone/fast

#=============================================================================
# Target rules for targets named StackImporter

# Build rule for target.
StackImporter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StackImporter
.PHONY : StackImporter

# fast build rule for target.
StackImporter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackImporter.dir/build.make CMakeFiles/StackImporter.dir/build
.PHONY : StackImporter/fast

Backend/Parser/parser.o: Backend/Parser/parser.cpp.o
.PHONY : Backend/Parser/parser.o

# target to build an object file
Backend/Parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackImporter.dir/build.make CMakeFiles/StackImporter.dir/Backend/Parser/parser.cpp.o
.PHONY : Backend/Parser/parser.cpp.o

Backend/Parser/parser.i: Backend/Parser/parser.cpp.i
.PHONY : Backend/Parser/parser.i

# target to preprocess a source file
Backend/Parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackImporter.dir/build.make CMakeFiles/StackImporter.dir/Backend/Parser/parser.cpp.i
.PHONY : Backend/Parser/parser.cpp.i

Backend/Parser/parser.s: Backend/Parser/parser.cpp.s
.PHONY : Backend/Parser/parser.s

# target to generate assembly for a file
Backend/Parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackImporter.dir/build.make CMakeFiles/StackImporter.dir/Backend/Parser/parser.cpp.s
.PHONY : Backend/Parser/parser.cpp.s

Backend/src/main.o: Backend/src/main.cpp.o
.PHONY : Backend/src/main.o

# target to build an object file
Backend/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackClone.dir/build.make CMakeFiles/StackClone.dir/Backend/src/main.cpp.o
.PHONY : Backend/src/main.cpp.o

Backend/src/main.i: Backend/src/main.cpp.i
.PHONY : Backend/src/main.i

# target to preprocess a source file
Backend/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackClone.dir/build.make CMakeFiles/StackClone.dir/Backend/src/main.cpp.i
.PHONY : Backend/src/main.cpp.i

Backend/src/main.s: Backend/src/main.cpp.s
.PHONY : Backend/src/main.s

# target to generate assembly for a file
Backend/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StackClone.dir/build.make CMakeFiles/StackClone.dir/Backend/src/main.cpp.s
.PHONY : Backend/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... StackClone"
	@echo "... StackImporter"
	@echo "... Backend/Parser/parser.o"
	@echo "... Backend/Parser/parser.i"
	@echo "... Backend/Parser/parser.s"
	@echo "... Backend/src/main.o"
	@echo "... Backend/src/main.i"
	@echo "... Backend/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

